spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # par défaut "dev" si non défini

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/report_gen_builder}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:iheb1118}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  default-produces-media-type: application/json

server:
  address: 0.0.0.0         # obligatoire pour Render (écoute sur toutes les interfaces)
  port: ${PORT:8080}       # Render injecte automatiquement PORT=10000
  servlet:
    context-path: /api/v1/
